version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=on
      - POSTGRES_USER=cooders
      - POSTGRES_PASSWORD=cooders1234
      - POSTGRES_DB=cooders_db
      - POSTGRES_HOST=database

  database:
    container_name: database
    image: "postgres" # use latest official postgres version
    environment:
    - POSTGRES_USER=cooders
    - POSTGRES_PASSWORD=cooders1234
    - POSTGRES_DB=cooders_db
    ports:
      - 5432:5432
    volumes:
    - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose